### PR TITLE
Remove item _People-first data stacks_ from TODO list

### PR DESCRIPTION
**Pull request by JordiCarreraVentura**

### CODE REVIEW

**Review by ronikobrosly — DISMISSED** [review]
LGTM! 👍 
It's great to collaborate with you @JordiCarreraVentura

**Comment by ronikobrosly** [comment]
Actually @JordiCarreraVentura , it looks like you might have accidentally removed the `data governance` link at the top instead of augmenting it to 3 posts

**Comment by JordiCarreraVentura** [comment]
@ronikobrosly You're totally right, sorry about that! I forgot to push my last commit 🤦‍♂️ Just did, I think it should be fixed. Please check again 🙏

**Review by ronikobrosly — APPROVED** [review]
Nice!

**Comment by JordiCarreraVentura** [comment]
@ronikobrosly Thanks man🤝😎

**Pull request merged**
