### PR TITLE
Update Data Science Interview Book link

### PR DESCRIPTION
**Pull request by erictleung**
Link was updated to a new one. So this PR updates it.

### CODE REVIEW

**Review by ronikobrosly — APPROVED** [review]
Thanks so much for updating the link! Feel free to contribute more / anytime you'd like. I'll let you merge.

**Comment by erictleung** [comment]
Thanks, @ronikobrosly ! Would love to contribute more as I find them. Happy to help merge if I got access.

**Comment by ronikobrosly** [comment]
@erictleung Im on vacation and only have the GitHub app on my phone, so for now I'll merge it myself and when I get back home I'll use my laptop to get you merge privileges 👍🏼

**Comment by erictleung** [comment]
Thanks @ronikobrosly for merging on your vacay! Hope it's a good one. I'll look out for a notification later on. Happy holidays!

**Comment by ronikobrosly** [comment]
Ok @erictleung , I just added you as a collaborator! Whenever we add or update links let's still include each other in PR reviews

**Comment by erictleung** [comment]
@ronikobrosly sounds good. Thanks for adding me!

**Pull request merged**
